// Spanish source copy used by live application screens; RU and EN stay paired.
export const localizationAuditCatalog: Record<string, { ru: string; en: string }> = {
  "Sin restricción": { ru: "Без ограничений", en: "No restriction" },
  "Tipo de propiedad": { ru: "Тип объекта", en: "Property type" },
  "Precio por noche": { ru: "Цена за ночь", en: "Price per night" },
  "Precio por mes": { ru: "Цена за месяц", en: "Price per month" },
  "Desde": { ru: "От", en: "From" },
  "Precio mínimo": { ru: "Минимальная цена", en: "Minimum price" },
  "Precio máximo": { ru: "Максимальная цена", en: "Maximum price" },
  "Qué se alquila": { ru: "Что сдаётся", en: "Rental unit" },
  "Plaza / cama": { ru: "Спальное место", en: "Bed space" },
  "Mínimo de camas": { ru: "Минимум кроватей", en: "Minimum beds" },
  "Capacidad de la habitación": { ru: "Вместимость комнаты", en: "Room capacity" },
  "Ya viven en esta habitación": { ru: "Уже живут в комнате", en: "Already in this room" },
  "Plazas libres mínimas": { ru: "Минимум свободных мест", en: "Minimum free spaces" },
  "Disponible para esta fecha": { ru: "Доступно на дату", en: "Available for this date" },
  "Disponible hasta al menos": { ru: "Доступно как минимум до", en: "Available until at least" },
  "Estancia mínima aceptada": { ru: "Допустимый минимальный срок", en: "Accepted minimum stay" },
  "Estancia mínima: hasta (noches)": { ru: "Минимальный срок — не более (ночей)", en: "Minimum stay up to (nights)" },
  "Últimas 24 horas": { ru: "За последние 24 часа", en: "Last 24 hours" },
  "Últimos 7 días": { ru: "За последние 7 дней", en: "Last 7 days" },
  "Últimos 30 días": { ru: "За последние 30 дней", en: "Last 30 days" },
  "Condiciones destacadas": { ru: "Основные условия", en: "Highlighted conditions" },
  "Vivienda y convivencia": { ru: "Квартира и жильцы", en: "Home and household" },
  "Vivienda desde (m²)": { ru: "Площадь жилья от (м²)", en: "Home size from (m²)" },
  "Vivienda desde": { ru: "Площадь жилья от", en: "Home size from" },
  "Vivienda hasta (m²)": { ru: "Площадь жилья до (м²)", en: "Home size to (m²)" },
  "Vivienda hasta": { ru: "Площадь жилья до", en: "Home size to" },
  "Baños en la vivienda: mínimo": { ru: "Санузлов в жилье: минимум", en: "Bathrooms in home: minimum" },
  "Mínimo de baños": { ru: "Минимум санузлов", en: "Minimum bathrooms" },
  "Residentes actuales": { ru: "Сейчас живут", en: "Current residents" },
  "Composición de la vivienda": { ru: "Состав жильцов", en: "Household composition" },
  "Mixto": { ru: "Совместное проживание", en: "Mixed" },
  "Hay niños en la vivienda": { ru: "В квартире есть дети", en: "Children live in the home" },
  "Central": { ru: "Центральное", en: "Central" },
  "Quién puede alojarse": { ru: "Кого принимают", en: "Who can stay" },
  "Niños": { ru: "Дети", en: "Children" },
  "Fianza y anunciante": { ru: "Депозит и арендодатель", en: "Deposit and advertiser" },
  "Tipo de anunciante": { ru: "Тип арендодателя", en: "Advertiser type" },
  "Filtra por habitación, plazas, vivienda, convivencia y disponibilidad.": { ru: "Фильтруйте по комнате, местам, квартире, жильцам и датам.", en: "Filter by room, spaces, home, household and availability." },
  "Limpiar": { ru: "Сбросить", en: "Clear" },
  "Mostrar resultados": { ru: "Показать результаты", en: "Show results" },
  "Filtros de búsqueda": { ru: "Фильтры поиска", en: "Search filters" },
  "Recibe avisos cuando haya habitaciones nuevas que encajen.": { ru: "Получайте уведомления о новых подходящих комнатах.", en: "Get alerts when matching rooms appear." },
  'Volver': { ru: 'Назад', en: 'Back' },
  'Ver': { ru: 'Открыть', en: 'View' },
  'Cerrar': { ru: 'Закрыть', en: 'Close' },
  'Cargando…': { ru: 'Загрузка…', en: 'Loading…' },
  'Notificaciones': { ru: 'Уведомления', en: 'Notifications' },
  'Entorno de demostración con datos locales.': { ru: 'Демонстрационная среда с локальными данными.', en: 'Demo environment with local data.' },
  'Título': { ru: 'Заголовок', en: 'Title' },
  'Borrar filtros': { ru: 'Сбросить фильтры', en: 'Clear filters' },
  'Borrar filtros (': { ru: 'Сбросить фильтры (', en: 'Clear filters (' },
  'Borrar (': { ru: 'Сбросить (', en: 'Clear (' },
  'Todas las fotos': { ru: 'Все фотографии', en: 'All photos' },
  'Enlace copiado': { ru: 'Ссылка скопирована', en: 'Link copied' },
  'Anuncio descartado de la búsqueda': { ru: 'Объявление скрыто из поиска', en: 'Listing hidden from search' },
  'Anuncio descartado': { ru: 'Объявление скрыто', en: 'Listing hidden' },
  'No se pudo compartir el anuncio': { ru: 'Не удалось поделиться объявлением', en: 'Could not share the listing' },
  'Llamar': { ru: 'Позвонить', en: 'Call' },
  'Ocultar anuncio': { ru: 'Скрыть объявление', en: 'Hide listing' },
  'Añadir a favoritos': { ru: 'Добавить в избранное', en: 'Add to favorites' },
  'Acciones del anuncio': { ru: 'Действия с объявлением', en: 'Listing actions' },
  'Enviar enlace del anuncio': { ru: 'Отправить ссылку на объявление', en: 'Send listing link' },
  'Denunciar anunciante': { ru: 'Пожаловаться на владельца', en: 'Report advertiser' },
  'Denunciar a': { ru: 'Пожаловаться на', en: 'Report' },
  'La denuncia se asociará al anunciante y usará «': { ru: 'Жалоба будет связана с владельцем, а объявление «', en: 'The report will be linked to the advertiser and use “' },
  '» como contexto. No compartiremos tu identidad con el anunciante.': { ru: '» будет использовано для контекста. Мы не раскроем вашу личность владельцу.', en: '” as context. We will not share your identity with the advertiser.' },
  'Denuncia sobre el anunciante enviada': { ru: 'Жалоба на владельца отправлена', en: 'Advertiser report submitted' },
  'Denuncia enviada': { ru: 'Жалоба отправлена', en: 'Report submitted' },
  'No se pudo enviar la denuncia': { ru: 'Не удалось отправить жалобу', en: 'Could not submit the report' },
  'Spam o comportamiento abusivo': { ru: 'Спам или оскорбительное поведение', en: 'Spam or abusive behavior' },
  'Identidad sospechosa': { ru: 'Подозрительная личность', en: 'Suspicious identity' },
  'Contenido discriminatorio': { ru: 'Дискриминационный контент', en: 'Discriminatory content' },
  'Otro motivo': { ru: 'Другая причина', en: 'Other reason' },
  'Capacidad:': { ru: 'Вместимость:', en: 'Capacity:' },
  'Ya viven en esta habitación:': { ru: 'Уже живут в этой комнате:', en: 'Already living in this room:' },
  'Plazas libres:': { ru: 'Свободных мест:', en: 'Available spaces:' },
  'Superficie de la habitación:': { ru: 'Площадь комнаты:', en: 'Room size:' },
  'Superficie total:': { ru: 'Общая площадь:', en: 'Total size:' },
  'Disponible hasta': { ru: 'Доступно до', en: 'Available until' },
  'Primero mostramos zona y precio parecidos.': { ru: 'Сначала показываем похожие районы и цены.', en: 'Similar areas and prices are shown first.' },
  'Anuncio directo': { ru: 'Прямое объявление', en: 'Direct listing' },
  'Consultar con el anunciante': { ru: 'Уточните у владельца', en: 'Ask the advertiser' },
  'Consultar disponibilidad': { ru: 'Уточните доступность', en: 'Ask about availability' },
  'Consulta disponibilidad': { ru: 'Уточните доступность', en: 'Ask about availability' },
  'Consultar estancia mínima': { ru: 'Уточните минимальный срок', en: 'Ask about minimum stay' },
  'Consultar fianza': { ru: 'Уточните депозит', en: 'Ask about deposit' },
  'Consultar gastos': { ru: 'Уточните расходы', en: 'Ask about bills' },
  'Gastos no incluidos': { ru: 'Расходы не включены', en: 'Bills not included' },
  'Gastos no especificados': { ru: 'Расходы не указаны', en: 'Bills not specified' },
  'Cuenta verificada': { ru: 'Подтверждённый аккаунт', en: 'Verified account' },
  'Cuenta local': { ru: 'Локальный аккаунт', en: 'Local account' },
  'Requisito': { ru: 'Требование', en: 'Requirement' },
  'Residentes': { ru: 'Жильцы', en: 'Residents' },
  'Capacidad': { ru: 'Вместимость', en: 'Capacity' },
  'Fumar': { ru: 'Курение', en: 'Smoking' },
  'Cargando resultados…': { ru: 'Загрузка результатов…', en: 'Loading results…' },
  'No se pudieron cargar los resultados.': { ru: 'Не удалось загрузить результаты.', en: 'Could not load results.' },
  'Cargando favoritos…': { ru: 'Загрузка избранного…', en: 'Loading favorites…' },
  'No se pudieron cargar los favoritos.': { ru: 'Не удалось загрузить избранное.', en: 'Could not load favorites.' },
  'Recibe avisos con los filtros y zona actuales.': { ru: 'Получайте уведомления с текущими фильтрами и районом.', en: 'Get alerts for the current filters and area.' },
  'Lista sincronizada con el mapa': { ru: 'Список синхронизирован с картой', en: 'List synchronized with the map' },
  'Acciones de resultados': { ru: 'Действия с результатами', en: 'Result actions' },
  'Mapa de habitaciones en Tenerife': { ru: 'Карта комнат на Тенерифе', en: 'Map of rooms in Tenerife' },
  'En esta versión solo puedes buscar habitaciones en Tenerife. Prueba Tenerife, Adeje, Arona, Santa Cruz o La Laguna.': { ru: 'В этой версии можно искать комнаты только на Тенерифе. Попробуйте Tenerife, Adeje, Arona, Santa Cruz или La Laguna.', en: 'In this version you can only search for rooms in Tenerife. Try Tenerife, Adeje, Arona, Santa Cruz or La Laguna.' },
  'Ajusta las condiciones y revisa cuántas habitaciones coinciden.': { ru: 'Выберите условия и проверьте количество подходящих комнат.', en: 'Adjust the conditions and check how many rooms match.' },
  'Prueba a ampliar el precio, quitar una condición o recuperar anuncios descartados.': { ru: 'Попробуйте расширить диапазон цен, убрать условие или вернуть скрытые объявления.', en: 'Try widening the price range, removing a condition or restoring hidden listings.' },
  'Precio por': { ru: 'Цена за', en: 'Price per' },
  'Cuenta y anuncios': { ru: 'Аккаунт и объявления', en: 'Account and listings' },
  'Ayuda y legal': { ru: 'Помощь и правовая информация', en: 'Help and legal' },
  'Publicidad destacada': { ru: 'Рекомендуемая реклама', en: 'Featured advertising' },
  'Busco vivienda': { ru: 'Ищу жильё', en: 'Looking for a home' },
  'Publico vivienda': { ru: 'Размещаю жильё', en: 'Listing a home' },
  'Recibe avisos sin repetir los mismos filtros.': { ru: 'Получайте уведомления без повторного выбора фильтров.', en: 'Get alerts without repeating the same filters.' },
  'Vacacional': { ru: 'Для отдыха', en: 'Holiday' },
  'Activar': { ru: 'Включить', en: 'Enable' },
  'Guarda una búsqueda desde los resultados.': { ru: 'Сохраните поиск на странице результатов.', en: 'Save a search from the results.' },
  'Controla tus datos públicos y preferencias.': { ru: 'Управляйте публичными данными и настройками.', en: 'Manage your public details and preferences.' },
  'Busca habitación': { ru: 'Ищет комнату', en: 'Looking for a room' },
  'Cuenta demo verificada': { ru: 'Подтверждённый демо-аккаунт', en: 'Verified demo account' },
  'Eliminar foto': { ru: 'Удалить фото', en: 'Remove photo' },
  'Permitir WhatsApp': { ru: 'Разрешить WhatsApp', en: 'Allow WhatsApp' },
  'Se muestra solo tras confirmar las condiciones': { ru: 'Показывается после подтверждения условий', en: 'Shown only after confirming the conditions' },
  'Gestiona el estado y rendimiento de tus anuncios.': { ru: 'Управляйте статусом и результатами объявлений.', en: 'Manage your listings’ status and performance.' },
  'Cerrado por el anunciante.': { ru: 'Закрыто владельцем.', en: 'Closed by the advertiser.' },
  'Anuncio publicado de nuevo': { ru: 'Объявление опубликовано повторно', en: 'Listing republished' },
  'Anuncio enviado a revisión': { ru: 'Объявление отправлено на проверку', en: 'Listing submitted for review' },
  'Volver a publicar': { ru: 'Опубликовать повторно', en: 'Republish' },
  'Anuncio cerrado': { ru: 'Объявление закрыто', en: 'Listing closed' },
  'Cerrar anuncio': { ru: 'Закрыть объявление', en: 'Close listing' },
  'No hay anuncios en este estado': { ru: 'Нет объявлений с этим статусом', en: 'No listings in this status' },
  'Crea uno nuevo o cambia el filtro.': { ru: 'Создайте новое объявление или измените фильтр.', en: 'Create a new listing or change the filter.' },
  'Abierta': { ru: 'Открыта', en: 'Open' },
  'Panel de administración': { ru: 'Панель администратора', en: 'Administration panel' },
  'Tu cuenta sigue funcionando como una cuenta normal. Usa este acceso solo cuando necesites moderar la plataforma.': { ru: 'Ваш аккаунт продолжает работать как обычный. Используйте этот доступ для модерации платформы.', en: 'Your account continues to work normally. Use this access when you need to moderate the platform.' },
  'Verifica tu identidad con Google': { ru: 'Подтвердите личность через Google', en: 'Verify your identity with Google' },
  'La administración requiere una identidad de Google verificada para esta misma dirección de correo.': { ru: 'Для администрирования требуется подтверждение Google с этим же адресом электронной почты.', en: 'Administration requires a verified Google identity for this same email address.' },
  'Verificar con Google': { ru: 'Подтвердить через Google', en: 'Verify with Google' },
  'Se eliminarán esta cuenta local, su sesión, anuncios, borrador, búsquedas, favoritos, historial, comentarios y archivos multimedia sin uso. Esta acción no se puede deshacer.': { ru: 'Будут удалены локальный аккаунт, сессия, объявления, черновик, поиски, избранное, история, комментарии и неиспользуемые медиафайлы. Это действие нельзя отменить.', en: 'This local account, session, listings, draft, searches, favorites, history, comments and unused media will be deleted. This action cannot be undone.' },
  'Todo el anuncio está en una sola página. Baja, completa los datos y publica al final.': { ru: 'Всё объявление на одной странице. Заполните данные и опубликуйте внизу.', en: 'The entire listing is on one page. Scroll down, complete the details and publish at the end.' },
  'Todo el anuncio está en una sola página. Baja, cambia lo que necesites y guarda al final.': { ru: 'Всё объявление на одной странице. Внесите изменения и сохраните внизу.', en: 'The entire listing is on one page. Scroll down, make your changes and save at the end.' },
  'Cambios sin guardar': { ru: 'Несохранённые изменения', en: 'Unsaved changes' },
  'Restablecer': { ru: 'Сбросить', en: 'Reset' },
  '¿Restablecer el borrador?': { ru: 'Сбросить черновик?', en: 'Reset the draft?' },
  'Se eliminarán los cambios del anuncio y las fotos temporales que no usa ningún anuncio guardado.': { ru: 'Будут удалены изменения объявления и временные фото, не используемые сохранёнными объявлениями.', en: 'Listing changes and temporary photos unused by saved listings will be deleted.' },
  'El anuncio ya está creado.': { ru: 'Объявление уже создано.', en: 'The listing has already been created.' },
  'Solo faltan las fotografías. Los demás campos quedan bloqueados hasta terminar la sincronización para evitar perder cambios.': { ru: 'Осталось добавить фотографии. Остальные поля заблокированы до завершения синхронизации, чтобы сохранить изменения.', en: 'Only the photos are missing. Other fields remain locked until synchronization finishes to preserve changes.' },
  'Coordenadas exactas:': { ru: 'Точные координаты:', en: 'Exact coordinates:' },
  'Habitación y vivienda': { ru: 'Комната и жильё', en: 'Room and home' },
  'Superficie habitación (m²)': { ru: 'Площадь комнаты (м²)', en: 'Room size (m²)' },
  'Superficie vivienda (m²)': { ru: 'Площадь жилья (м²)', en: 'Home size (m²)' },
  'Baños': { ru: 'Ванные комнаты', en: 'Bathrooms' },
  'Capacidad habitación': { ru: 'Вместимость комнаты', en: 'Room capacity' },
  'Personas ya en la habitación': { ru: 'Уже проживают в комнате', en: 'People already in the room' },
  'Sótano': { ru: 'Подвал', en: 'Basement' },
  'Selecciona': { ru: 'Выберите', en: 'Select' },
  'Accesible': { ru: 'Доступно для маломобильных', en: 'Accessible' },
  'Alquiler mensual (€)': { ru: 'Аренда в месяц (€)', en: 'Monthly rent (€)' },
  'Precio semanal (€)': { ru: 'Цена за неделю (€)', en: 'Weekly price (€)' },
  'Fianza (€)': { ru: 'Депозит (€)', en: 'Deposit (€)' },
  'Gastos aproximados al mes (€)': { ru: 'Примерные расходы в месяц (€)', en: 'Approximate monthly bills (€)' },
  'Gastos incluidos en el precio': { ru: 'Расходы включены в цену', en: 'Bills included in the price' },
  'Gastos aparte': { ru: 'Расходы отдельно', en: 'Bills extra' },
  'Convivencia y requisitos': { ru: 'Совместное проживание и требования', en: 'Household and requirements' },
  'A quién buscas': { ru: 'Кого вы ищете', en: 'Who you are looking for' },
  'Perfiles aceptados': { ru: 'Кого принимают', en: 'Accepted tenants' },
  'Hombre': { ru: 'Мужчина', en: 'Man' },
  'Mujer': { ru: 'Женщина', en: 'Woman' },
  'Familia': { ru: 'Семья', en: 'Family' },
  'Se aceptan mascotas': { ru: 'Можно с животными', en: 'Pets accepted' },
  'Se permite fumar': { ru: 'Можно курить', en: 'Smoking allowed' },
  'Se aceptan menores': { ru: 'Можно с детьми', en: 'Children accepted' },
  'Ya viven menores': { ru: 'Уже проживают дети', en: 'Children already live here' },
  'No se permiten enlaces ni dominios externos.': { ru: 'Внешние ссылки и домены запрещены.', en: 'External links and domains are not allowed.' },
  'No se permiten enlaces, dominios ni direcciones web en los anuncios.': { ru: 'Ссылки, домены и веб-адреса в объявлениях запрещены.', en: 'Links, domains and web addresses are not allowed in listings.' },
  'Título y descripción': { ru: 'Заголовок и описание', en: 'Title and description' },
  'Mostrar WhatsApp': { ru: 'Показывать WhatsApp', en: 'Show WhatsApp' },
  'Confirma tu email para publicar': { ru: 'Подтвердите email для публикации', en: 'Confirm your email to publish' },
  'Enviaremos un código de seis dígitos a': { ru: 'Отправим шестизначный код на', en: 'We will send a six-digit code to' },
  'Código no válido.': { ru: 'Неверный код.', en: 'Invalid code.' },
  'Confirmar y publicar': { ru: 'Подтвердить и опубликовать', en: 'Confirm and publish' },
  '¿Salir del editor?': { ru: 'Выйти из редактора?', en: 'Leave the editor?' },
  'Hay cambios sin guardar. El borrador automático se conserva, pero puedes guardarlo manualmente antes de salir.': { ru: 'Есть несохранённые изменения. Автоматический черновик сохранится, но вы можете сохранить его вручную перед выходом.', en: 'There are unsaved changes. The automatic draft is kept, but you can save it manually before leaving.' },
  'Seguir editando': { ru: 'Продолжить редактирование', en: 'Keep editing' },
  'Salir y conservar borrador': { ru: 'Выйти и сохранить черновик', en: 'Leave and keep draft' },
  'Editar anuncio': { ru: 'Редактировать объявление', en: 'Edit listing' },
  'Publicando…': { ru: 'Публикация…', en: 'Publishing…' },
  'Procesando foto…': { ru: 'Обработка фото…', en: 'Processing photo…' },
  'Procesando vídeo…': { ru: 'Обработка видео…', en: 'Processing video…' },
  'Reintentar fotos': { ru: 'Повторить загрузку фото', en: 'Retry photos' },
  'Procesando la foto…': { ru: 'Обработка фото…', en: 'Processing photo…' },
  'Procesando el vídeo…': { ru: 'Обработка видео…', en: 'Processing video…' },
  'Falta terminar las fotografías': { ru: 'Нужно завершить загрузку фото', en: 'Photos still need to finish' },
  'El borrador tiene cambios': { ru: 'В черновике есть изменения', en: 'The draft has changes' },
  'Borrador guardado automáticamente': { ru: 'Черновик сохранён автоматически', en: 'Draft saved automatically' },
  'El giro ya se muestra; terminamos de guardar la imagen.': { ru: 'Поворот уже виден; завершаем сохранение изображения.', en: 'The rotation is already visible; the image is finishing saving.' },
  'Terminamos de preparar el vídeo antes de publicar.': { ru: 'Завершаем подготовку видео перед публикацией.', en: 'Finishing video preparation before publishing.' },
  'Revisamos todos los campos antes de publicar.': { ru: 'Проверяем все поля перед публикацией.', en: 'Checking all fields before publishing.' },
  'Reintentar fotografías': { ru: 'Повторить загрузку фотографий', en: 'Retry photos' },
  'Tienes cambios sin guardar': { ru: 'Есть несохранённые изменения', en: 'You have unsaved changes' },
  'Todo guardado': { ru: 'Всё сохранено', en: 'Everything saved' },
  'Terminamos de preparar el vídeo antes de guardar.': { ru: 'Завершаем подготовку видео перед сохранением.', en: 'Finishing video preparation before saving.' },
  'Revisamos todos los campos al guardar.': { ru: 'Проверяем все поля при сохранении.', en: 'Checking all fields when saving.' },
  'Arrastra o selecciona JPEG, PNG o WebP · máximo': { ru: 'Перетащите или выберите JPEG, PNG или WebP · максимум', en: 'Drag or select JPEG, PNG or WebP · maximum' },
  'Añadir fotos del anuncio': { ru: 'Добавить фото объявления', en: 'Add listing photos' },
  'Usar como portada': { ru: 'Сделать обложкой', en: 'Use as cover' },
  'Girar': { ru: 'Повернуть', en: 'Rotate' },
  'Vídeo del anuncio': { ru: 'Видео объявления', en: 'Listing video' },
  'Vídeo de la vivienda': { ru: 'Видео жилья', en: 'Home video' },
  'Recorrido de hasta 1 minuto': { ru: 'Обзор до 1 минуты', en: 'Tour of up to 1 minute' },
  'Opcional · 1 vídeo · máximo': { ru: 'Необязательно · 1 видео · максимум', en: 'Optional · 1 video · maximum' },
  'segundos · MP4/MOV · hasta': { ru: 'секунд · MP4/MOV · до', en: 'seconds · MP4/MOV · up to' },
  'Preparando…': { ru: 'Подготовка…', en: 'Preparing…' },
  'Añadir vídeo': { ru: 'Добавить видео', en: 'Add video' },
  'Añadir vídeo del anuncio': { ru: 'Добавить видео объявления', en: 'Add listing video' },
  'Vista previa del vídeo del anuncio': { ru: 'Предпросмотр видео объявления', en: 'Listing video preview' },
  'Cargando vista previa…': { ru: 'Загрузка предпросмотра…', en: 'Loading preview…' },
  'Sustituir vídeo': { ru: 'Заменить видео', en: 'Replace video' },
  'Eliminar vídeo': { ru: 'Удалить видео', en: 'Remove video' },
  'Selecciona un municipio válido.': { ru: 'Выберите допустимый муниципалитет.', en: 'Select a valid municipality.' },
  'Indica la zona o barrio.': { ru: 'Укажите район.', en: 'Enter the area or neighborhood.' },
  'La zona no puede superar 120 caracteres.': { ru: 'Название района не может превышать 120 символов.', en: 'The area cannot exceed 120 characters.' },
  'La calle no puede superar 160 caracteres.': { ru: 'Название улицы не может превышать 160 символов.', en: 'The street cannot exceed 160 characters.' },
  'El código postal debe tener exactamente 5 dígitos.': { ru: 'Почтовый индекс должен содержать ровно 5 цифр.', en: 'The postcode must contain exactly 5 digits.' },
  'El código postal debe tener 5 dígitos.': { ru: 'Почтовый индекс должен содержать 5 цифр.', en: 'The postcode must contain 5 digits.' },
  'Indica entre 1 y 200 m².': { ru: 'Укажите от 1 до 200 м².', en: 'Enter between 1 and 200 m².' },
  'Debe ser igual o mayor que la habitación.': { ru: 'Площадь должна быть не меньше площади комнаты.', en: 'Must be at least as large as the room.' },
  'Indica al menos una habitación.': { ru: 'Укажите хотя бы одну комнату.', en: 'Enter at least one room.' },
  'Indica un número válido.': { ru: 'Укажите допустимое число.', en: 'Enter a valid number.' },
  'La capacidad debe estar entre 1 y 10.': { ru: 'Вместимость должна быть от 1 до 10.', en: 'Capacity must be between 1 and 10.' },
  'Indica entre 1 y 10 camas.': { ru: 'Укажите от 1 до 10 кроватей.', en: 'Enter between 1 and 10 beds.' },
  'Debe quedar al menos una plaza libre.': { ru: 'Должно оставаться хотя бы одно свободное место.', en: 'At least one space must be available.' },
  'Las plazas individuales solo se pueden alquilar en una habitación compartida.': { ru: 'Отдельные места можно сдавать только в общей комнате.', en: 'Individual spaces can only be rented in a shared room.' },
  'Las plazas independientes no usan cama doble.': { ru: 'Для отдельных мест не используется двуспальная кровать.', en: 'Individual spaces do not use a double bed.' },
  'Las camas indicadas no cubren la capacidad.': { ru: 'Указанных кроватей недостаточно для заявленной вместимости.', en: 'The specified beds do not cover the capacity.' },
  'Selecciona una opción.': { ru: 'Выберите вариант.', en: 'Select an option.' },
  'Indica un precio válido.': { ru: 'Укажите допустимую цену.', en: 'Enter a valid price.' },
  'El precio semanal debe ser válido.': { ru: 'Цена за неделю должна быть допустимой.', en: 'The weekly price must be valid.' },
  'La fianza no puede ser negativa.': { ru: 'Депозит не может быть отрицательным.', en: 'The deposit cannot be negative.' },
  'Indica el gasto aproximado al mes.': { ru: 'Укажите примерные расходы в месяц.', en: 'Enter approximate monthly bills.' },
  'Selecciona una fecha.': { ru: 'Выберите дату.', en: 'Select a date.' },
  'La fecha final debe ser posterior.': { ru: 'Дата окончания должна быть позже даты начала.', en: 'The end date must be later.' },
  'Indica al menos 1 mes.': { ru: 'Укажите не менее 1 месяца.', en: 'Enter at least 1 month.' },
  'Indica al menos 1 noche.': { ru: 'Укажите не менее 1 ночи.', en: 'Enter at least 1 night.' },
  'Vuelve a añadir las fotografías no disponibles.': { ru: 'Добавьте недоступные фотографии заново.', en: 'Add the unavailable photos again.' },
  'Vuelve a añadir el vídeo no disponible.': { ru: 'Добавьте недоступное видео заново.', en: 'Add the unavailable video again.' },
  'Escribe un título de al menos 15 caracteres.': { ru: 'Введите заголовок длиной не менее 15 символов.', en: 'Enter a title of at least 15 characters.' },
  'La descripción debe tener entre 40 y 10.000 caracteres.': { ru: 'Описание должно содержать от 40 до 10 000 символов.', en: 'The description must contain between 40 and 10,000 characters.' },
  'Las normas no pueden superar 10.000 caracteres.': { ru: 'Правила не могут превышать 10 000 символов.', en: 'The rules cannot exceed 10,000 characters.' },
  'No se pudo publicar el anuncio.': { ru: 'Не удалось опубликовать объявление.', en: 'Could not publish the listing.' },
  'No se pudieron guardar los cambios.': { ru: 'Не удалось сохранить изменения.', en: 'Could not save changes.' },
  'No se pudo guardar el borrador. Revisa el espacio disponible.': { ru: 'Не удалось сохранить черновик. Проверьте свободное место.', en: 'Could not save the draft. Check available space.' },
  'No se pudo guardar el borrador restablecido.': { ru: 'Не удалось сохранить сброшенный черновик.', en: 'Could not save the reset draft.' },
  'Borrador restablecido': { ru: 'Черновик сброшен', en: 'Draft reset' },
  'El nombre público debe tener entre 2 y 120 caracteres.': { ru: 'Публичное имя должно содержать от 2 до 120 символов.', en: 'The public name must contain between 2 and 120 characters.' },
  'El nombre debe tener al menos 2 caracteres.': { ru: 'Имя должно содержать не менее 2 символов.', en: 'The name must contain at least 2 characters.' },
  'Introduce un teléfono válido.': { ru: 'Введите допустимый номер телефона.', en: 'Enter a valid phone number.' },
  'Introduce un teléfono para mostrarlo.': { ru: 'Введите номер телефона для показа.', en: 'Enter a phone number to display it.' },
  'Introduce un WhatsApp para mostrarlo.': { ru: 'Введите номер WhatsApp для показа.', en: 'Enter a WhatsApp number to display it.' },
  'Activa teléfono o WhatsApp como forma de contacto.': { ru: 'Включите телефон или WhatsApp для связи.', en: 'Enable phone or WhatsApp as a contact method.' },
  'Valor no válido.': { ru: 'Недопустимое значение.', en: 'Invalid value.' },
  'Revisa los datos del formulario.': { ru: 'Проверьте данные формы.', en: 'Check the form details.' },
  'No se pudo completar la solicitud.': { ru: 'Не удалось выполнить запрос.', en: 'Could not complete the request.' },
  'La solicitud tardó demasiado.': { ru: 'Запрос занял слишком много времени.', en: 'The request took too long.' },
  'No se pudo conectar con el servidor.': { ru: 'Не удалось подключиться к серверу.', en: 'Could not connect to the server.' },
  'No se pudo cargar la imagen.': { ru: 'Не удалось загрузить изображение.', en: 'Could not load the image.' },
  'El servidor devolvió un archivo de imagen no válido.': { ru: 'Сервер вернул недопустимый файл изображения.', en: 'The server returned an invalid image file.' },
  'No se encontró la imagen.': { ru: 'Изображение не найдено.', en: 'Image not found.' },
  'No se pudo leer la imagen.': { ru: 'Не удалось прочитать изображение.', en: 'Could not read the image.' },
  'No se encontró una de las imágenes locales.': { ru: 'Одно из локальных изображений не найдено.', en: 'One of the local images was not found.' },
  'No se encontró el vídeo local.': { ru: 'Локальное видео не найдено.', en: 'The local video was not found.' },
  'Una de las imágenes ya no está disponible. Vuelve a añadirla.': { ru: 'Одно из изображений больше недоступно. Добавьте его заново.', en: 'One of the images is no longer available. Add it again.' },
  'El vídeo ya no está disponible. Vuelve a añadirlo.': { ru: 'Видео больше недоступно. Добавьте его заново.', en: 'The video is no longer available. Add it again.' },
  'El archivo no es una imagen válida.': { ru: 'Файл не является допустимым изображением.', en: 'The file is not a valid image.' },
  'La imagen ya está en su orientación original.': { ru: 'Изображение уже в исходной ориентации.', en: 'The image is already in its original orientation.' },
  'No se pudo abrir la imagen.': { ru: 'Не удалось открыть изображение.', en: 'Could not open the image.' },
  'No se pudo girar la imagen.': { ru: 'Не удалось повернуть изображение.', en: 'Could not rotate the image.' },
  'No se pudo guardar la imagen girada.': { ru: 'Не удалось сохранить повёрнутое изображение.', en: 'Could not save the rotated image.' },
  'No se pudo leer o guardar una de las imágenes.': { ru: 'Не удалось прочитать или сохранить одно из изображений.', en: 'Could not read or save one of the images.' },
  'No se pudo leer el vídeo.': { ru: 'Не удалось прочитать видео.', en: 'Could not read the video.' },
  'El archivo no es un vídeo válido.': { ru: 'Файл не является допустимым видео.', en: 'The file is not a valid video.' },
  'No se pudo abrir la vista previa del vídeo.': { ru: 'Не удалось открыть предпросмотр видео.', en: 'Could not open the video preview.' },
  'Formato de vídeo no compatible. Usa MP4 o MOV.': { ru: 'Неподдерживаемый формат видео. Используйте MP4 или MOV.', en: 'Unsupported video format. Use MP4 or MOV.' },
  'No se pudo leer o guardar el vídeo.': { ru: 'Не удалось прочитать или сохранить видео.', en: 'Could not read or save the video.' },
  'El almacenamiento de imágenes no está disponible.': { ru: 'Хранилище изображений недоступно.', en: 'Image storage is unavailable.' },
  'No se pudo abrir el almacenamiento de imágenes.': { ru: 'Не удалось открыть хранилище изображений.', en: 'Could not open image storage.' },
  'No hay espacio suficiente para guardar el archivo.': { ru: 'Недостаточно места для сохранения файла.', en: 'Not enough space to save the file.' },
  'No se pudo leer o guardar el archivo.': { ru: 'Не удалось прочитать или сохранить файл.', en: 'Could not read or save the file.' },
  'Formato no compatible. Usa JPEG, PNG o WebP.': { ru: 'Неподдерживаемый формат. Используйте JPEG, PNG или WebP.', en: 'Unsupported format. Use JPEG, PNG or WebP.' },
  'El vídeo no puede superar 100 MB.': { ru: 'Размер видео не может превышать 100 MB.', en: 'The video cannot exceed 100 MB.' },
  'El vídeo no puede durar más de 1 minuto.': { ru: 'Видео не может длиться дольше 1 минуты.', en: 'The video cannot be longer than 1 minute.' },
  'No se pudieron limpiar algunas imágenes locales.': { ru: 'Не удалось удалить некоторые локальные изображения.', en: 'Could not clean up some local images.' },
  'No se pudieron limpiar las imágenes locales.': { ru: 'Не удалось удалить локальные изображения.', en: 'Could not clean up local images.' },
  'No se pudo limpiar el avatar temporal.': { ru: 'Не удалось удалить временный аватар.', en: 'Could not clean up the temporary avatar.' },
  'No se pudo guardar el avatar.': { ru: 'Не удалось сохранить аватар.', en: 'Could not save the avatar.' },
  'No se pudo limpiar el avatar anterior.': { ru: 'Не удалось удалить предыдущий аватар.', en: 'Could not clean up the previous avatar.' },
  'No hay espacio suficiente. Tus últimos cambios no se han guardado.': { ru: 'Недостаточно места. Последние изменения не сохранены.', en: 'Not enough space. Your latest changes were not saved.' },
  'Había datos locales dañados. Se ha cargado una copia segura.': { ru: 'Локальные данные были повреждены. Загружена безопасная копия.', en: 'Local data was corrupted. A safe copy was loaded.' },
  'No se pudo guardar en este navegador. Revisa la privacidad o el espacio disponible.': { ru: 'Не удалось сохранить данные в браузере. Проверьте настройки приватности и свободное место.', en: 'Could not save in this browser. Check privacy settings or available space.' },
  'Se produjo un error inesperado al publicar. Inténtalo de nuevo.': { ru: 'При публикации произошла неожиданная ошибка. Повторите попытку.', en: 'An unexpected error occurred while publishing. Try again.' },
  'Confirma tu email antes de publicar el anuncio.': { ru: 'Подтвердите email перед публикацией объявления.', en: 'Confirm your email before publishing the listing.' },
  'Tu cuenta tiene restringida la publicación de anuncios. Revisa el aviso de moderación.': { ru: 'Публикация объявлений ограничена для вашего аккаунта. Проверьте уведомление модерации.', en: 'Your account is restricted from publishing listings. Check the moderation notice.' },
  'Has alcanzado el límite de anuncios activos.': { ru: 'Вы достигли лимита активных объявлений.', en: 'You have reached the active listing limit.' },
  'Necesitas una cuenta de anfitrión autorizada para publicar.': { ru: 'Для публикации нужен авторизованный аккаунт владельца.', en: 'You need an authorized host account to publish.' },
  'Tu sesión ha caducado. Inicia sesión de nuevo para publicar.': { ru: 'Сессия истекла. Войдите снова для публикации.', en: 'Your session has expired. Sign in again to publish.' },
  'La publicación está tardando más de lo esperado. Comprobaremos el mismo intento para evitar duplicados.': { ru: 'Публикация занимает больше времени, чем ожидалось. Проверим эту же попытку, чтобы избежать дубликатов.', en: 'Publishing is taking longer than expected. We will check the same attempt to avoid duplicates.' },
  'No se pudo conectar con el servidor. Revisa tu conexión e inténtalo de nuevo.': { ru: 'Не удалось подключиться к серверу. Проверьте соединение и повторите попытку.', en: 'Could not connect to the server. Check your connection and try again.' },
  'Revisa los datos del anuncio antes de publicarlo.': { ru: 'Проверьте данные объявления перед публикацией.', en: 'Check the listing details before publishing.' },
  'El servidor no pudo completar la publicación. Inténtalo de nuevo más tarde.': { ru: 'Сервер не смог завершить публикацию. Повторите попытку позже.', en: 'The server could not complete publishing. Try again later.' },
  'No se pudo publicar el anuncio. Revisa los datos e inténtalo de nuevo.': { ru: 'Не удалось опубликовать объявление. Проверьте данные и повторите попытку.', en: 'Could not publish the listing. Check the details and try again.' },
  'Necesitas una cuenta de anfitrión para publicar.': { ru: 'Для публикации нужен аккаунт владельца.', en: 'You need a host account to publish.' },
  'Termina la recuperación de las fotografías del anuncio anterior antes de publicar otro.': { ru: 'Завершите восстановление фото предыдущего объявления перед публикацией нового.', en: 'Finish recovering the previous listing’s photos before publishing another.' },
  'Las fotos se guardaron, pero no se pudo refrescar el catálogo.': { ru: 'Фотографии сохранены, но каталог не удалось обновить.', en: 'Photos were saved, but the catalog could not be refreshed.' },
  'Las fotografías se han sincronizado y el anuncio está listo.': { ru: 'Фотографии синхронизированы, объявление готово.', en: 'Photos have synchronized and the listing is ready.' },
  'El anuncio ya está creado, pero las fotografías siguen pendientes. Revisa las fotos y vuelve a intentarlo.': { ru: 'Объявление уже создано, но фотографии ещё не загружены. Проверьте фото и повторите попытку.', en: 'The listing is already created, but photos are still pending. Check them and try again.' },
  'No se pudieron preparar las fotos o el vídeo.': { ru: 'Не удалось подготовить фотографии или видео.', en: 'Could not prepare the photos or video.' },
  'El anuncio se guardó, pero no se pudo refrescar el catálogo.': { ru: 'Объявление сохранено, но каталог не удалось обновить.', en: 'The listing was saved, but the catalog could not be refreshed.' },
  'Anuncio enviado a moderación y guardado en Mis anuncios': { ru: 'Объявление отправлено на модерацию и сохранено в «Моих объявлениях»', en: 'Listing submitted for moderation and saved in My listings' },
  'No puedes gestionar un anuncio de otra cuenta.': { ru: 'Нельзя управлять объявлением другого аккаунта.', en: 'You cannot manage another account’s listing.' },
  'Los cambios se guardaron, pero no se pudo refrescar el catálogo.': { ru: 'Изменения сохранены, но каталог не удалось обновить.', en: 'Changes were saved, but the catalog could not be refreshed.' },
  'No tienes permiso para eliminar este anuncio.': { ru: 'У вас нет прав на удаление этого объявления.', en: 'You do not have permission to delete this listing.' },
  'No se pudo eliminar el anuncio en el servidor.': { ru: 'Не удалось удалить объявление на сервере.', en: 'Could not delete the listing on the server.' },
  'El anuncio se eliminó, pero no se pudo refrescar el catálogo.': { ru: 'Объявление удалено, но каталог не удалось обновить.', en: 'The listing was deleted, but the catalog could not be refreshed.' },
  'No se pudo moderar el anuncio en el servidor.': { ru: 'Не удалось выполнить модерацию объявления на сервере.', en: 'Could not moderate the listing on the server.' },
  'El estado se guardó, pero no se pudo refrescar el catálogo.': { ru: 'Статус сохранён, но каталог не удалось обновить.', en: 'The status was saved, but the catalog could not be refreshed.' },
  'No se pudo actualizar el estado del anuncio en el servidor.': { ru: 'Не удалось обновить статус объявления на сервере.', en: 'Could not update the listing status on the server.' },
  'La renovación se guardó, pero no se pudo refrescar el catálogo.': { ru: 'Продление сохранено, но каталог не удалось обновить.', en: 'The renewal was saved, but the catalog could not be refreshed.' },
  'No se pudo renovar el anuncio en el servidor.': { ru: 'Не удалось продлить объявление на сервере.', en: 'Could not renew the listing on the server.' },
  'No se pudo enviar la denuncia al servidor.': { ru: 'Не удалось отправить жалобу на сервер.', en: 'Could not submit the report to the server.' },
  'No se pudo restaurar la sesión.': { ru: 'Не удалось восстановить сессию.', en: 'Could not restore the session.' },
  'No se pudieron sincronizar los datos de tu cuenta.': { ru: 'Не удалось синхронизировать данные аккаунта.', en: 'Could not synchronize your account data.' },
  'No se pudo sincronizar el historial de búsqueda.': { ru: 'Не удалось синхронизировать историю поиска.', en: 'Could not synchronize search history.' },
  'No se pudieron cargar tus anuncios.': { ru: 'Не удалось загрузить ваши объявления.', en: 'Could not load your listings.' },
  'No se pudo actualizar el catálogo.': { ru: 'Не удалось обновить каталог.', en: 'Could not refresh the catalog.' },
  'No se pudieron cargar las denuncias.': { ru: 'Не удалось загрузить жалобы.', en: 'Could not load reports.' },
  'No se pudieron cargar los usuarios.': { ru: 'Не удалось загрузить пользователей.', en: 'Could not load users.' },
  'No se pudo sincronizar el favorito.': { ru: 'Не удалось синхронизировать избранное.', en: 'Could not synchronize the favorite.' },
  'Eliminado de favoritos': { ru: 'Удалено из избранного', en: 'Removed from favorites' },
  'Guardado en favoritos': { ru: 'Сохранено в избранном', en: 'Saved to favorites' },
  'No se pudo sincronizar el anuncio oculto.': { ru: 'Не удалось синхронизировать скрытое объявление.', en: 'Could not synchronize the hidden listing.' },
  'No se pudieron restaurar los anuncios.': { ru: 'Не удалось восстановить объявления.', en: 'Could not restore listings.' },
  'No se pudo guardar el historial de búsqueda.': { ru: 'Не удалось сохранить историю поиска.', en: 'Could not save search history.' },
  'No se pudo borrar el historial de búsqueda.': { ru: 'Не удалось удалить историю поиска.', en: 'Could not clear search history.' },
  'Esta búsqueda ya está guardada': { ru: 'Этот поиск уже сохранён', en: 'This search is already saved' },
  'No se pudo guardar la búsqueda.': { ru: 'Не удалось сохранить поиск.', en: 'Could not save the search.' },
  'Búsqueda guardada. Te avisaremos de nuevos anuncios.': { ru: 'Поиск сохранён. Мы сообщим о новых объявлениях.', en: 'Search saved. We will notify you about new listings.' },
  'No se pudo eliminar la búsqueda guardada.': { ru: 'Не удалось удалить сохранённый поиск.', en: 'Could not delete the saved search.' },
  'No se pudieron actualizar las alertas.': { ru: 'Не удалось обновить уведомления.', en: 'Could not update alerts.' },
  'No se pudo iniciar sesión. Inténtalo de nuevo.': { ru: 'Не удалось войти. Повторите попытку.', en: 'Could not sign in. Try again.' },
  'No se pudo iniciar sesión con Google.': { ru: 'Не удалось войти через Google.', en: 'Could not sign in with Google.' },
  'No se pudo guardar tu elección.': { ru: 'Не удалось сохранить ваш выбор.', en: 'Could not save your choice.' },
  'No se pudo crear la cuenta. Inténtalo de nuevo.': { ru: 'Не удалось создать аккаунт. Повторите попытку.', en: 'Could not create the account. Try again.' },
  'No se pudo guardar el perfil en el servidor.': { ru: 'Не удалось сохранить профиль на сервере.', en: 'Could not save the profile on the server.' },
  'No se pudo guardar el avatar en el servidor.': { ru: 'Не удалось сохранить аватар на сервере.', en: 'Could not save the avatar on the server.' },
  'No se pudo eliminar la cuenta en el servidor.': { ru: 'Не удалось удалить аккаунт на сервере.', en: 'Could not delete the account on the server.' },
  'No se pudieron limpiar todos los datos multimedia de la cuenta.': { ru: 'Не удалось удалить все медиафайлы аккаунта.', en: 'Could not clean up all account media.' },
  'No se pudo actualizar el estado de la cuenta.': { ru: 'Не удалось обновить статус аккаунта.', en: 'Could not update the account status.' },
  'El servidor no confirmó la ubicación guardada. Los cambios no se marcarán como guardados.': { ru: 'Сервер не подтвердил сохранённое местоположение. Изменения не будут отмечены как сохранённые.', en: 'The server did not confirm the saved location. Changes will not be marked as saved.' },
  'Mapa no disponible': { ru: 'Карта недоступна', en: 'Map unavailable' },
  'Mapa de resultados': { ru: 'Карта результатов', en: 'Results map' },
  'Google Maps con precios de habitaciones': { ru: 'Google Maps с ценами комнат', en: 'Google Maps with room prices' },
  'Mantén pulsado y dibuja el contorno de la zona': { ru: 'Нажмите и удерживайте, чтобы нарисовать границы зоны', en: 'Press and hold to draw the area outline' },
  'Cargando Google Maps': { ru: 'Загрузка Google Maps', en: 'Loading Google Maps' },
  'Mapa de desarrollo: configura un Map ID propio antes de publicar.': { ru: 'Карта разработки: настройте собственный Map ID перед публикацией.', en: 'Development map: configure your own Map ID before publishing.' },
  'Alternativa textual al mapa': { ru: 'Текстовая альтернатива карте', en: 'Text alternative to the map' },
  'Anuncio TOP': { ru: 'Объявление TOP', en: 'TOP listing' },
  'Anuncio anterior en esta dirección': { ru: 'Предыдущее объявление по этому адресу', en: 'Previous listing at this address' },
  'Siguiente anuncio en esta dirección': { ru: 'Следующее объявление по этому адресу', en: 'Next listing at this address' },
  'Anuncio siguiente en esta dirección': { ru: 'Следующее объявление по этому адресу', en: 'Next listing at this address' },
  'No se pudieron cargar los anuncios del mapa. Mueve el mapa para reintentar.': { ru: 'Не удалось загрузить объявления на карте. Переместите карту для повторной попытки.', en: 'Could not load map listings. Move the map to retry.' },
  'No se pudieron cargar los anuncios. Mueve el mapa para reintentar.': { ru: 'Не удалось загрузить объявления. Переместите карту для повторной попытки.', en: 'Could not load listings. Move the map to retry.' },
  'No se pudieron cargar los límites seleccionados. El resto del mapa sigue disponible.': { ru: 'Не удалось загрузить выбранные границы. Остальная карта доступна.', en: 'Could not load the selected boundaries. The rest of the map remains available.' },
  'Modo dibujo activado. La zona dibujada sustituye a las zonas municipales. Añade al menos 3 puntos.': { ru: 'Режим рисования включён. Нарисованная зона заменяет муниципальные зоны. Добавьте не менее 3 точек.', en: 'Drawing mode enabled. The drawn area replaces municipal areas. Add at least 3 points.' },
  'Zona dibujada eliminada.': { ru: 'Нарисованная зона удалена.', en: 'Drawn area deleted.' },
  'Resultados actualizados para el área visible.': { ru: 'Результаты обновлены для видимой области.', en: 'Results updated for the visible area.' },
  'Seleccionar zonas de Tenerife': { ru: 'Выбрать районы Тенерифе', en: 'Select areas in Tenerife' },
  'Buscar municipio, distrito o barrio': { ru: 'Найти муниципалитет, округ или район', en: 'Search municipality, district or neighborhood' },
  'Las zonas administrativas y la zona dibujada son alternativas. Aplicar una sustituye a la otra.': { ru: 'Административные районы и нарисованная зона являются альтернативами. Выбор одного заменяет другое.', en: 'Administrative areas and the drawn area are alternatives. Applying one replaces the other.' },
  'Jerarquía de zonas': { ru: 'Иерархия районов', en: 'Area hierarchy' },
  'Resultados de zonas': { ru: 'Результаты районов', en: 'Area results' },
  'Municipios de Tenerife': { ru: 'Муниципалитеты Тенерифе', en: 'Municipalities of Tenerife' },
  'Distrito': { ru: 'Округ', en: 'District' },
  'Barrio': { ru: 'Район', en: 'Neighborhood' },
  'Isla': { ru: 'Остров', en: 'Island' },
  'No hay zonas publicadas que coincidan.': { ru: 'Нет опубликованных районов, соответствующих поиску.', en: 'No published areas match.' },
  'Google Maps con municipios, distritos y barrios de Tenerife': { ru: 'Google Maps с муниципалитетами, округами и районами Тенерифе', en: 'Google Maps with municipalities, districts and neighborhoods of Tenerife' },
  'Cargando límites administrativos…': { ru: 'Загрузка административных границ…', en: 'Loading administrative boundaries…' },
  'Puedes seguir usando la lista de zonas.': { ru: 'Можно продолжить пользоваться списком районов.', en: 'You can continue using the area list.' },
  'Límites: Cabildo de Tenerife (CC BY), ISTAC y Ayuntamiento de Santa Cruz de Tenerife (CC BY)': { ru: 'Границы: Cabildo de Tenerife (CC BY), ISTAC и Ayuntamiento de Santa Cruz de Tenerife (CC BY)', en: 'Boundaries: Cabildo de Tenerife (CC BY), ISTAC and Ayuntamiento de Santa Cruz de Tenerife (CC BY)' },
  'Los límites detallados no están disponibles ahora; se mantienen los 31 municipios.': { ru: 'Подробные границы сейчас недоступны; сохранены 31 муниципалитет.', en: 'Detailed boundaries are unavailable; the 31 municipalities remain.' },
  'No se pudieron cargar los límites geográficos.': { ru: 'Не удалось загрузить географические границы.', en: 'Could not load geographic boundaries.' },
  'Lugares de Tenerife': { ru: 'Места на Тенерифе', en: 'Places in Tenerife' },
  'También puedes': { ru: 'Также можно', en: 'You can also' },
  'Cargando zonas…': { ru: 'Загрузка районов…', en: 'Loading areas…' },
  'Explora municipios, distritos y barrios con límites oficiales disponibles.': { ru: 'Исследуйте муниципалитеты, округа и районы с доступными официальными границами.', en: 'Explore municipalities, districts and neighborhoods with available official boundaries.' },
  'No se pudo resolver esta dirección.': { ru: 'Не удалось определить этот адрес.', en: 'Could not resolve this address.' },
  'La clave de Google Maps no autoriza este dominio. Revisa las restricciones HTTP referrer en Google Cloud.': { ru: 'Ключ Google Maps не разрешает этот домен. Проверьте ограничения HTTP referrer в Google Cloud.', en: 'The Google Maps key does not authorize this domain. Check HTTP referrer restrictions in Google Cloud.' },
  'Configura VITE_GOOGLE_MAPS_API_KEY en .env.local para mostrar el mapa.': { ru: 'Настройте VITE_GOOGLE_MAPS_API_KEY в .env.local для показа карты.', en: 'Configure VITE_GOOGLE_MAPS_API_KEY in .env.local to display the map.' },
  'Configura VITE_GOOGLE_MAPS_MAP_ID para usar marcadores avanzados en producción.': { ru: 'Настройте VITE_GOOGLE_MAPS_MAP_ID для расширенных маркеров в рабочей среде.', en: 'Configure VITE_GOOGLE_MAPS_MAP_ID to use advanced markers in production.' },
  'Google Maps no pudo cargarse. Revisa que Maps JavaScript API esté habilitada y que este dominio esté permitido.': { ru: 'Не удалось загрузить Google Maps. Проверьте, что Maps JavaScript API включён и этот домен разрешён.', en: 'Google Maps could not load. Check that Maps JavaScript API is enabled and this domain is allowed.' },
  'Tus datos de acceso se procesan de forma segura': { ru: 'Ваши данные для входа обрабатываются безопасно', en: 'Your sign-in details are processed securely' },
  'Usa al menos 12 caracteres.': { ru: 'Используйте не менее 12 символов.', en: 'Use at least 12 characters.' },
  'Mínimo 12 caracteres.': { ru: 'Не менее 12 символов.', en: 'At least 12 characters.' },
  'Tu sesión ya está activa.': { ru: 'Вы уже вошли в аккаунт.', en: 'Your session is already active.' },
  'Registro completado': { ru: 'Регистрация завершена', en: 'Registration complete' },
  'La cuenta se ha creado en esta demostración y ya puedes continuar.': { ru: 'Аккаунт создан в демо-версии. Можно продолжить.', en: 'The account was created in this demo and you can continue.' },
  'La cuenta se ha creado. Podrás confirmar tu email con un código cuando publiques tu primer anuncio.': { ru: 'Аккаунт создан. Подтвердить email кодом можно при публикации первого объявления.', en: 'The account was created. You can confirm your email with a code when publishing your first listing.' },
  'No se pudo solicitar el restablecimiento.': { ru: 'Не удалось запросить сброс пароля.', en: 'Could not request a password reset.' },
  'Te enviaremos un enlace seguro para crear una contraseña nueva.': { ru: 'Мы отправим безопасную ссылку для создания нового пароля.', en: 'We will send a secure link to create a new password.' },
  'Solicitud registrada': { ru: 'Запрос зарегистрирован', en: 'Request recorded' },
  'Si existe una cuenta con ese email, recibirás las instrucciones de restablecimiento.': { ru: 'Если аккаунт с этим email существует, вы получите инструкции по сбросу пароля.', en: 'If an account exists with that email, you will receive reset instructions.' },
  'Crear nueva contraseña': { ru: 'Создать новый пароль', en: 'Create new password' },
  'Solicitar enlace': { ru: 'Запросить ссылку', en: 'Request link' },
  'El enlace de restablecimiento no es válido o ha caducado.': { ru: 'Ссылка для сброса пароля недействительна или истекла.', en: 'The reset link is invalid or has expired.' },
  'Las contraseñas deben coincidir y tener al menos 12 caracteres.': { ru: 'Пароли должны совпадать и содержать не менее 12 символов.', en: 'Passwords must match and contain at least 12 characters.' },
  'No se pudo actualizar la contraseña.': { ru: 'Не удалось обновить пароль.', en: 'Could not update the password.' },
  'Tu contraseña se ha actualizado y las sesiones anteriores se han cerrado.': { ru: 'Пароль обновлён, предыдущие сессии завершены.', en: 'Your password was updated and previous sessions were closed.' },
  'Introduce el código de seis dígitos.': { ru: 'Введите шестизначный код.', en: 'Enter the six-digit code.' },
  'No se pudo confirmar el correo.': { ru: 'Не удалось подтвердить email.', en: 'Could not confirm the email.' },
  'Correo confirmado': { ru: 'Email подтверждён', en: 'Email confirmed' },
  'Confirma tu correo': { ru: 'Подтвердите email', en: 'Confirm your email' },
  'Tu dirección de correo ya está verificada.': { ru: 'Ваш email уже подтверждён.', en: 'Your email address is already verified.' },
  'Solicita un código de seis dígitos antes de publicar tu anuncio.': { ru: 'Запросите шестизначный код перед публикацией объявления.', en: 'Request a six-digit code before publishing your listing.' },
  'Ya puedes publicar tu anuncio.': { ru: 'Теперь можно опубликовать объявление.', en: 'You can now publish your listing.' },
  'Confirmar correo': { ru: 'Подтвердить email', en: 'Confirm email' },
  'Código de seis dígitos': { ru: 'Шестизначный код', en: 'Six-digit code' },
  'Código enviado': { ru: 'Код отправлен', en: 'Code sent' },
  'Enviar código': { ru: 'Отправить код', en: 'Send code' },
  'No se pudo enviar el código.': { ru: 'Не удалось отправить код.', en: 'Could not send the code.' },
  'Restringir a': { ru: 'Ограничить', en: 'Restrict' },
  'Duración:': { ru: 'Длительность:', en: 'Duration:' },
  'Subir anuncio al TOP': { ru: 'Поднять объявление в TOP', en: 'Promote listing to TOP' },
  'Al terminar la fecha «Hasta», el anuncio dejará de estar en TOP automáticamente. No hace falta retirarlo manualmente.': { ru: 'В дату окончания объявление автоматически выйдет из TOP. Ручное снятие не требуется.', en: 'On the end date, the listing will automatically leave TOP. No manual removal is needed.' },
  'Publicidad en la portada': { ru: 'Реклама на главной', en: 'Homepage advertising' },
  'Ya existe otro anuncio configurado para la portada. Al guardar, este anuncio lo sustituirá.': { ru: 'Другое объявление уже настроено для главной страницы. При сохранении это объявление заменит его.', en: 'Another listing is already configured for the homepage. Saving this listing will replace it.' },
  'Al terminar «Hasta», la portada vuelve automáticamente a la imagen habitual. Si el anuncio deja de estar publicado, tampoco se mostrará.': { ru: 'В дату окончания главная страница автоматически вернётся к обычному изображению. Если объявление больше не опубликовано, оно также не будет показано.', en: 'On the end date, the homepage automatically returns to its usual image. The listing also stops appearing if it is no longer published.' },
  'Eliminar cuenta de': { ru: 'Удалить аккаунт', en: 'Delete account of' },
  'La cuenta se desactivará, dejará de ser accesible y sus anuncios desaparecerán de la parte pública. La auditoría y las denuncias se conservarán.': { ru: 'Аккаунт будет отключён и недоступен, а его объявления исчезнут из публичной части. Аудит и жалобы сохранятся.', en: 'The account will be deactivated and inaccessible, and its listings will disappear from public view. Audit records and reports will be kept.' },
  'Escribe DELETE para confirmar': { ru: 'Введите DELETE для подтверждения', en: 'Type DELETE to confirm' },
  'Esta cuenta está eliminada. La ficha se conserva únicamente como historial de moderación y es de solo lectura.': { ru: 'Аккаунт удалён. Карточка сохраняется только как история модерации и доступна лишь для чтения.', en: 'This account is deleted. Its record is kept only as moderation history and is read-only.' },
  'Esta cuenta es administradora. Para restringirla o eliminarla primero hay que revocar sus permisos en Ajustes → Administradores.': { ru: 'Этот аккаунт является администратором. Для ограничения или удаления сначала отзовите права в Настройках → Администраторы.', en: 'This account is an administrator. To restrict or delete it, first revoke its permissions in Settings → Administrators.' },
  'Los avisos de moderación incluyen el motivo, la fecha final —si existe— y esta dirección.': { ru: 'Уведомления модерации содержат причину, дату окончания, если она указана, и этот адрес.', en: 'Moderation notices include the reason, the end date if present, and this address.' },
  'Registro cronológico no editable.': { ru: 'Хронологический журнал без возможности редактирования.', en: 'Chronological record that cannot be edited.' },
  'Guardar nota': { ru: 'Сохранить заметку', en: 'Save note' },
  'Actualizar': { ru: 'Обновить', en: 'Refresh' },
  'Activos': { ru: 'Активные', en: 'Active' },
  'Eliminados': { ru: 'Удалённые', en: 'Deleted' },
  'Último acceso:': { ru: 'Последний вход:', en: 'Last sign-in:' },
  'Objetivo:': { ru: 'Объект:', en: 'Target:' },
  'Anuncio:': { ru: 'Объявление:', en: 'Listing:' },
  'Usuario:': { ru: 'Пользователь:', en: 'User:' },
  'Todos tienen los mismos permisos. No se puede eliminar el último administrador ni revocar tus propios permisos desde aquí.': { ru: 'У всех одинаковые права. Здесь нельзя удалить последнего администратора или отозвать собственные права.', en: 'Everyone has the same permissions. You cannot remove the last administrator or revoke your own permissions here.' },
  'Activo desde': { ru: 'Активен с', en: 'Active since' },
  'Se muestra al usuario en bloqueos, avisos y correos de moderación.': { ru: 'Показывается пользователю в блокировках, уведомлениях и письмах модерации.', en: 'Shown to the user in restrictions, notices and moderation emails.' },
  'El anuncio permanecerá oculto hasta que otro administrador retire manualmente la restricción.': { ru: 'Объявление останется скрытым, пока другой администратор не снимет ограничение вручную.', en: 'The listing will remain hidden until another administrator manually removes the restriction.' },
  'Canales de contacto': { ru: 'Каналы связи', en: 'Contact channels' },
  'Incluye la referencia del anuncio cuando corresponda': { ru: 'При необходимости укажите номер объявления', en: 'Include the listing reference where relevant' },
  'Describe el problema y los pasos para reproducirlo': { ru: 'Опишите проблему и шаги для её воспроизведения', en: 'Describe the problem and steps to reproduce it' },
  'Consulta preparada': { ru: 'Обращение подготовлено', en: 'Inquiry prepared' },
  'Para garantizar la entrega, envía también el mensaje a': { ru: 'Для гарантированной доставки также отправьте сообщение на', en: 'To ensure delivery, also send the message to' },
  'Preparar consulta': { ru: 'Подготовить обращение', en: 'Prepare inquiry' },
  'La experiencia se centra inicialmente en Tenerife y está preparada para ampliarse a otras islas y ciudades.': { ru: 'Сервис пока сосредоточен на Тенерифе и готов к расширению на другие острова и города.', en: 'The service initially focuses on Tenerife and is ready to expand to other islands and cities.' },
  'Confirma que cumples las condiciones y usa únicamente los canales habilitados por el anunciante.': { ru: 'Подтвердите соответствие условиям и используйте только каналы связи, указанные владельцем.', en: 'Confirm that you meet the conditions and use only the channels enabled by the advertiser.' },
  'Para publicar se confirma el email mediante un código de seis dígitos. Los anuncios pueden pasar por revisión y su estado aparece en Mis anuncios.': { ru: 'Для публикации email подтверждается шестизначным кодом. Объявления могут проходить проверку, их статус отображается в «Моих объявлениях».', en: 'Publishing requires email confirmation with a six-digit code. Listings may be reviewed and their status appears in My listings.' },
  'Condiciones generales para buscar, publicar y contactar a través de 112233.es.': { ru: 'Общие условия поиска, публикации и связи через 112233.es.', en: 'General conditions for searching, publishing and contacting through 112233.es.' },
  'Naturaleza del servicio': { ru: 'Характер сервиса', en: 'Nature of the service' },
  '112233.es facilita la publicación, búsqueda y contacto entre personas interesadas en habitaciones o estudios. No forma parte del contrato de alquiler ni garantiza identidad, solvencia o disponibilidad.': { ru: '112233.es помогает размещать объявления, искать жильё и связываться людям, заинтересованным в комнатах или студиях. Сервис не является стороной договора аренды и не гарантирует личность, платёжеспособность или доступность жилья.', en: '112233.es facilitates publishing, searching and contact between people interested in rooms or studios. It is not a party to rental contracts and does not guarantee identity, solvency or availability.' },
  'Responsabilidad al publicar': { ru: 'Ответственность при публикации', en: 'Responsibility when publishing' },
  'Quien publica debe disponer de autorización y mantener correctos el precio, fotografías, gastos, disponibilidad y condiciones. No se permiten duplicados, fraude, contenido ilícito ni direcciones exactas visibles.': { ru: 'Автор должен иметь разрешение на публикацию и поддерживать актуальность цены, фото, расходов, доступности и условий. Дубликаты, мошенничество, незаконный контент и публичные точные адреса запрещены.', en: 'Advertisers must be authorized and keep prices, photos, bills, availability and conditions accurate. Duplicates, fraud, illegal content and visible exact addresses are not allowed.' },
  'Moderación y seguridad': { ru: 'Модерация и безопасность', en: 'Moderation and security' },
  'Podemos revisar, rechazar, ocultar o retirar contenido y limitar cuentas ante fraude, abuso, incumplimiento, riesgo para terceros o requerimiento legal.': { ru: 'Мы можем проверять, отклонять, скрывать или удалять контент и ограничивать аккаунты при мошенничестве, злоупотреблении, нарушениях, риске для третьих лиц или по законному требованию.', en: 'We may review, reject, hide or remove content and restrict accounts in cases of fraud, abuse, violations, risks to third parties or legal requirements.' },
  'Pagos y acuerdos': { ru: 'Платежи и соглашения', en: 'Payments and agreements' },
  'Verifica la vivienda, la identidad y las condiciones antes de enviar dinero o documentación sensible. La plataforma no custodia depósitos ni responde por acuerdos privados fuera del servicio.': { ru: 'Проверьте жильё, личность и условия перед отправкой денег или конфиденциальных документов. Платформа не хранит депозиты и не отвечает за частные соглашения вне сервиса.', en: 'Verify the home, identity and conditions before sending money or sensitive documents. The platform does not hold deposits or take responsibility for private agreements outside the service.' },
  'Política de privacidad': { ru: 'Политика конфиденциальности', en: 'Privacy policy' },
  'Cómo utiliza 112233.es los datos necesarios para operar cuentas, anuncios, mapas y seguridad.': { ru: 'Как 112233.es использует данные для работы аккаунтов, объявлений, карт и безопасности.', en: 'How 112233.es uses data needed for accounts, listings, maps and security.' },
  'Datos tratados': { ru: 'Обрабатываемые данные', en: 'Data processed' },
  'Podemos tratar nombre, email, contraseña cifrada, rol, avatar, preferencias, sesiones, identificador técnico de Google, anuncios, fotografías, favoritos, búsquedas guardadas y registros de seguridad.': { ru: 'Мы можем обрабатывать имя, email, зашифрованный пароль, роль, аватар, настройки, сессии, технический идентификатор Google, объявления, фото, избранное, сохранённые поиски и журналы безопасности.', en: 'We may process names, email, encrypted passwords, roles, avatars, preferences, sessions, technical Google identifiers, listings, photos, favorites, saved searches and security records.' },
  'Finalidades': { ru: 'Цели', en: 'Purposes' },
  'Los datos se usan para autenticar cuentas, publicar y gestionar anuncios, mostrar resultados y mapas, facilitar contactos solicitados, recuperar contraseñas y prevenir abuso o fraude.': { ru: 'Данные используются для входа в аккаунты, публикации и управления объявлениями, показа результатов и карт, запрошенных контактов, восстановления паролей и предотвращения злоупотреблений и мошенничества.', en: 'Data is used to authenticate accounts, publish and manage listings, display results and maps, facilitate requested contact, recover passwords and prevent abuse or fraud.' },
  'Proveedores técnicos': { ru: 'Технические поставщики', en: 'Technical providers' },
  'La infraestructura utiliza PostgreSQL/PostGIS, Redis y MinIO. Google Identity Services y Google Maps prestan autenticación y mapas. Gmail SMTP envía códigos y avisos transaccionales.': { ru: 'Инфраструктура использует PostgreSQL/PostGIS, Redis и MinIO. Google Identity Services и Google Maps обеспечивают вход и карты. Gmail SMTP отправляет коды и служебные уведомления.', en: 'The infrastructure uses PostgreSQL/PostGIS, Redis and MinIO. Google Identity Services and Google Maps provide authentication and maps. Gmail SMTP sends codes and transactional notices.' },
  'La vista pública utiliza una posición aproximada. La dirección exacta, cuando se facilita para gestionar un anuncio, no debe mostrarse públicamente.': { ru: 'Публично показывается примерное местоположение. Точный адрес, предоставленный для управления объявлением, не должен отображаться публично.', en: 'The public view uses an approximate location. Exact addresses supplied to manage a listing must not be displayed publicly.' },
  'Conservación y derechos': { ru: 'Хранение и права', en: 'Retention and rights' },
  'Versión completa': { ru: 'Полная версия', en: 'Full version' },
  'La política completa y directamente accesible para usuarios y verificadores está disponible en /privacidad.': { ru: 'Полная политика, доступная пользователям и проверяющим, находится на /privacidad.', en: 'The full policy, directly accessible to users and reviewers, is available at /privacidad.' },
  'Información sobre cookies y almacenamiento local utilizados por 112233.es.': { ru: 'Информация о файлах cookie и локальном хранилище, используемых 112233.es.', en: 'Information about cookies and local storage used by 112233.es.' },
  'Mantienen la sesión, protegen la autenticación y permiten que las funciones esenciales respondan correctamente.': { ru: 'Они поддерживают сессию, защищают вход и обеспечивают работу основных функций.', en: 'They maintain sessions, protect authentication and allow essential functions to work correctly.' },
  'Almacenamiento local': { ru: 'Локальное хранилище', en: 'Local storage' },
  'Puede conservar preferencias de interfaz, favoritos y borradores del editor en el dispositivo utilizado.': { ru: 'Оно может сохранять настройки интерфейса, избранное и черновики редактора на устройстве.', en: 'It may store interface preferences, favorites and editor drafts on the device used.' },
  'Servicios externos': { ru: 'Внешние сервисы', en: 'External services' },
  'Google Identity Services y Google Maps pueden usar mecanismos técnicos propios conforme a sus políticas para prestar autenticación y mapas.': { ru: 'Google Identity Services и Google Maps могут использовать собственные технические механизмы согласно своим политикам для входа и карт.', en: 'Google Identity Services and Google Maps may use their own technical mechanisms according to their policies to provide authentication and maps.' },
  'Puede eliminar cookies y almacenamiento local desde el navegador. Al hacerlo se cerrará la sesión y pueden perderse preferencias o borradores guardados solo en ese dispositivo.': { ru: 'Вы можете удалить файлы cookie и локальное хранилище в браузере. Это завершит сессию и может удалить настройки или черновики, сохранённые только на этом устройстве.', en: 'You can delete cookies and local storage in the browser. This signs you out and may remove preferences or drafts saved only on that device.' },
  'Fraude, duplicados, contenido sexual, direcciones públicas, suplantación y criterios discriminatorios contrarios a la normativa aplicable.': { ru: 'Мошенничество, дубликаты, сексуальный контент, публичные адреса, выдача себя за другое лицо и дискриминационные критерии, противоречащие применимым правилам.', en: 'Fraud, duplicates, sexual content, public addresses, impersonation and discriminatory criteria contrary to applicable rules.' },
  'La campaña no se encontró.': { ru: 'Кампания не найдена.', en: 'Campaign not found.' },
  'La imagen publicitaria debe ser válida y pertenecer a esta cuenta.': { ru: 'Рекламное изображение должно быть допустимым и принадлежать этому аккаунту.', en: 'The advertisement image must be valid and owned by this account.' },
  'Se alcanzó el límite diario de campañas.': { ru: 'Достигнут дневной лимит кампаний.', en: 'The daily campaign limit was reached.' },
  'No se puede editar una campaña cancelada.': { ru: 'Нельзя редактировать отменённую кампанию.', en: 'A cancelled campaign cannot be edited.' },
  'El titular y la imagen de la campaña deben seguir activos.': { ru: 'Владелец и изображение кампании должны оставаться активными.', en: 'The campaign owner and image must still be active.' },
  'Las fechas de la campaña no son válidas.': { ru: 'Недопустимые даты кампании.', en: 'The campaign dates are invalid.' },
  'Se requiere una campaña pendiente de revisión.': { ru: 'Требуется кампания, ожидающая проверки.', en: 'A campaign pending review is required.' },
  'Se requiere una campaña activa.': { ru: 'Требуется активная кампания.', en: 'An active campaign is required.' },
  'El texto publicitario es demasiado corto.': { ru: 'Рекламный текст слишком короткий.', en: 'The advertising text is too short.' },
  'Solo se permite texto sin formato.': { ru: 'Допустим только обычный текст.', en: 'Only plain text is allowed.' },
  'Introduce un enlace web válido.': { ru: 'Введите допустимую веб-ссылку.', en: 'Enter a valid website URL.' },
  'Solo se permiten enlaces http y https.': { ru: 'Допустимы только ссылки http и https.', en: 'Only http and https links are allowed.' },
  'Se requiere un enlace web público.': { ru: 'Требуется публичная веб-ссылка.', en: 'A public website URL is required.' },
  'El puerto del enlace web no es válido.': { ru: 'Недопустимый порт веб-ссылки.', en: 'The website URL port is invalid.' },
  'Usa el prefijo internacional o un teléfono español de 9 dígitos.': { ru: 'Используйте международный код или испанский номер из 9 цифр.', en: 'Use the country code or a 9-digit Spanish phone number.' },
  'Introduce un correo electrónico válido.': { ru: 'Введите допустимый адрес электронной почты.', en: 'Enter a valid email address.' },
  'Selecciona un tipo de contacto válido.': { ru: 'Выберите допустимый тип контакта.', en: 'Select a valid contact type.' },
}

Object.assign(localizationAuditCatalog, {
  'Cerrar notificación': { ru: 'Закрыть уведомление', en: 'Close notification' },
  'No has permitido acceder a tu ubicación.': { ru: 'Доступ к местоположению отклонён.', en: 'Location permission was denied.' },
  'Tu ubicación no está disponible.': { ru: 'Местоположение недоступно.', en: 'Your location is unavailable.' },
  'La búsqueda de ubicación ha tardado demasiado.': { ru: 'Определение местоположения заняло слишком много времени.', en: 'Finding your location took too long.' },
  'Tu navegador no ofrece geolocalización.': { ru: 'Браузер не поддерживает геолокацию.', en: 'Your browser does not provide geolocation.' },
  'Tu ubicación está fuera de Tenerife.': { ru: 'Вы находитесь за пределами Тенерифе.', en: 'Your location is outside Tenerife.' },
  'de': { ru: 'из', en: 'of' },
  'imágenes': { ru: 'изображений', en: 'images' },
  'activos': { ru: 'активных', en: 'active' },
  'residentes ·': { ru: 'жильцов ·', en: 'residents ·' },
  'guardadas': { ru: 'сохранено', en: 'saved' },
  'anuncios locales': { ru: 'локальных объявлений', en: 'local listings' },
  '. Tu borrador y tus fotos seguirán guardados.': { ru: '. Ваш черновик и фотографии сохранятся.', en: '. Your draft and photos will stay saved.' },
  '· editado': { ru: '· изменено', en: '· edited' },
  'residentes actuales en la vivienda': { ru: 'жильцов сейчас проживает в жилье', en: 'current residents in the home' },
  '. Sus anuncios se ocultarán mientras exista la restricción. Se enviará un email y un aviso dentro de la cuenta.': { ru: '. Объявления будут скрыты, пока действует ограничение. Будут отправлены email и уведомление в аккаунте.', en: '. Their listings will be hidden while the restriction is active. An email and an account notice will be sent.' },
  '. El anuncio tendrá prioridad únicamente dentro del periodo seleccionado.': { ru: '. Объявление будет иметь приоритет только в выбранный период.', en: '. The listing will have priority only during the selected period.' },
  '/día · total': { ru: '/день · всего', en: '/day · total' },
  '. Durante el periodo activo, la primera foto de este anuncio sustituirá la imagen habitual de la portada.': { ru: '. В активный период первое фото этого объявления заменит обычное изображение на главной.', en: '. During the active period, this listing’s first photo will replace the usual homepage image.' },
  'asociados a esta cuenta': { ru: 'связано с этим аккаунтом', en: 'linked to this account' },
  'sobre sus anuncios o su cuenta': { ru: 'об объявлениях или аккаунте', en: 'about their listings or account' },
  'anuncios': { ru: 'объявлений', en: 'listings' },
  'visitas': { ru: 'просмотров', en: 'views' },
  'admin': { ru: 'админ', en: 'admin' },
  'Carrusel': { ru: 'Карусель', en: 'Carousel' },
  'Campo obligatorio': { ru: 'Обязательное поле', en: 'Required field' },
  'Inicia sesión para continuar': { ru: 'Войдите, чтобы продолжить', en: 'Sign in to continue' },
  'No encontrado': { ru: 'Не найдено', en: 'Not found' },
  'Quitar de favoritos': { ru: 'Убрать из избранного', en: 'Remove from favorites' },
  'Este anuncio busca a un hombre': { ru: 'Это объявление для мужчины', en: 'This listing is looking for a man' },
  'Este anuncio busca a una mujer': { ru: 'Это объявление для женщины', en: 'This listing is looking for a woman' },
  'Este anuncio ya existe. Sustituye las fotografías.': { ru: 'Такое объявление уже существует. Замените фотографии.', en: 'This listing already exists. Replace the photos.' },
  'No se pudieron guardar los cambios del anuncio.': { ru: 'Не удалось сохранить изменения объявления.', en: 'The listing changes could not be saved.' },
  'Tu sesión ha caducado. Inicia sesión de nuevo y vuelve a guardar.': { ru: 'Сессия истекла. Войдите снова и повторите сохранение.', en: 'Your session has expired. Sign in again and retry the save.' },
  'No tienes permiso para editar este anuncio.': { ru: 'У вас нет доступа к редактированию этого объявления.', en: 'You do not have permission to edit this listing.' },
  'El guardado ha tardado demasiado. Inténtalo de nuevo.': { ru: 'Сохранение заняло слишком много времени. Повторите попытку.', en: 'Saving took too long. Please try again.' },
  'Revisa los datos del anuncio y vuelve a guardar.': { ru: 'Проверьте данные объявления и повторите сохранение.', en: 'Check the listing details and try saving again.' },
  'El servidor no pudo guardar los cambios. Inténtalo de nuevo más tarde.': { ru: 'Сервер не смог сохранить изменения. Повторите попытку позже.', en: 'The server could not save the changes. Try again later.' },
  'La campaña no está pendiente de pago.': { ru: 'Кампания не ожидает оплаты.', en: 'The campaign is not awaiting payment.' },
  'Se requiere una campaña pagada y pendiente de revisión.': { ru: 'Требуется оплаченная кампания, ожидающая проверки.', en: 'A paid campaign pending review is required.' },
  'No se pudo guardar el archivo subido.': { ru: 'Не удалось сохранить загруженный файл.', en: 'Could not save the uploaded file.' },
})

// Server messages are aliases of canonical UI copy, never locale-specific API values.
export const localizationSourceAliases: Record<string, string> = {
  Close: 'Cerrar',
  Loading: 'Cargando…',
  'Advertisement not found': 'La campaña no se encontró.',
  'A valid advertisement image owned by this account is required': 'La imagen publicitaria debe ser válida y pertenecer a esta cuenta.',
  'Daily advertisement submission limit reached': 'Se alcanzó el límite diario de campañas.',
  'Cancelled advertisement cannot be edited': 'No se puede editar una campaña cancelada.',
  'Advertisement owner and image must still be active': 'El titular y la imagen de la campaña deben seguir activos.',
  'Invalid advertisement schedule': 'Las fechas de la campaña no son válidas.',
  'Pending-review advertisement required': 'Se requiere una campaña pendiente de revisión.',
  'Active advertisement required': 'Se requiere una campaña activa.',
  'Advertisement is not awaiting payment': 'La campaña no está pendiente de pago.',
  'Paid pending-review advertisement required': 'Se requiere una campaña pagada y pendiente de revisión.',
  'Uploaded media was not persisted': 'No se pudo guardar el archivo subido.',
  'Advertising text is too short': 'El texto publicitario es demasiado corto.',
  'Plain text only': 'Solo se permite texto sin formato.',
  'Invalid website URL': 'Introduce un enlace web válido.',
  'Only http and https website URLs are allowed': 'Solo se permiten enlaces http y https.',
  'A public website URL is required': 'Se requiere un enlace web público.',
  'Invalid website port': 'El puerto del enlace web no es válido.',
  'Invalid phone number': 'Introduce un teléfono válido.',
  'Use +country code, or a 9-digit Spanish phone number': 'Usa el prefijo internacional o un teléfono español de 9 dígitos.',
  'Invalid email address': 'Introduce un correo electrónico válido.',
  'Invalid destination type': 'Selecciona un tipo de contacto válido.',
  'Field required': 'Campo obligatorio',
  'Input should be a valid integer': 'Indica un número válido.',
  'Input should be a valid number': 'Indica un número válido.',
  'Not authenticated': 'Inicia sesión para continuar',
  'Not Found': 'No encontrado',
}
