export { occupantPersonIcon } from './person'
export { occupantCoupleIcon } from './couple'
export { occupantManIcon } from './man'
export { occupantWomanIcon } from './woman'
export { occupantFamilyIcon } from './family-ref'
export { occupantPetsIcon } from './pets-ref'
export { occupantAnyIcon } from './any-ref'
