import { expect, test, type Page } from '@playwright/test'

async function finishOnboarding(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await page.getByRole('button', { name: 'Ahora no' }).click()
  await expect(page.getByTestId('open-location')).toBeVisible()
}

test.describe('mobile history', () => {
  test.use({ viewport: { width: 390, height: 844 } })

  test('Home → results → map → detail unwinds one visible screen at a time', async ({ page }) => {
    await finishOnboarding(page)
    await page.locator('.m2-mode-switch > button').first().click()
    await page.getByTestId('open-location').click()
    const results = page.getByTestId('mobile-results')
    await expect(results.locator('.m2-result-card').first()).toBeVisible()
    const resultsUrl = page.url()
    await results.getByRole('button', { name: 'Mapa' }).click()
    const map = page.getByTestId('google-map')
    await expect(map).toHaveAttribute('data-map-interaction', 'interactive', { timeout: 20_000 })
    const originalZoom = Number(await map.getAttribute('data-map-zoom'))
    await map.evaluate((element) => element.dispatchEvent(new WheelEvent('wheel', { bubbles: true, deltaY: -100 })))
    await expect.poll(async () => Number(await map.getAttribute('data-map-zoom'))).toBeGreaterThan(originalZoom)
    const marker = page.locator('.m2-listing-marker').first()
    await expect(marker).toBeAttached()
    await marker.evaluate((element) => element.dispatchEvent(new MouseEvent('click', { bubbles: true })))
    const preview = page.getByTestId('mobile-map-listing-preview')
    await expect(preview).toBeVisible()
    const listingId = await preview.getAttribute('data-listing-id')
    await expect(page).toHaveURL(/mapLat=.*mapLng=.*mapZoom=/)
    const camera = await map.evaluate((element) => ({ center: element.dataset.mapCenter, zoom: element.dataset.mapZoom }))
    await preview.locator('.m2-map-listing-preview__open').click()
    await expect(page).toHaveURL(new RegExp(`#/habitacion/${encodeURIComponent(listingId!)}$`))
    await expect(page.locator('.listing-page h1')).toBeVisible()
    await page.getByRole('button', { name: 'Volver', exact: true }).click()
    await expect(map).toBeVisible()
    await expect(page).toHaveURL(new RegExp(`mapSelected=${encodeURIComponent(listingId!)}`))
    await expect(preview).toHaveAttribute('data-listing-id', listingId!)
    await expect.poll(async () => map.getAttribute('data-map-center')).not.toBeNull()
    const restoredCamera = await map.evaluate((element) => ({ center: element.dataset.mapCenter, zoom: element.dataset.mapZoom }))
    const [beforeLat, beforeLng] = camera.center!.split(',').map(Number)
    const [afterLat, afterLng] = restoredCamera.center!.split(',').map(Number)
    expect(Math.abs(afterLat - beforeLat)).toBeLessThan(0.00002)
    expect(Math.abs(afterLng - beforeLng)).toBeLessThan(0.00002)
    expect(Number(restoredCamera.zoom)).toBeCloseTo(Number(camera.zoom), 2)
    await expect(page.getByTestId('mobile-results')).toHaveCount(0)
    await page.goBack()
    await expect(page).toHaveURL(resultsUrl)
    await expect(results.locator('.m2-result-card').first()).toBeVisible()
    await page.goBack()
    await expect(page.getByTestId('open-location')).toBeVisible()
    await page.goForward()
    await expect(results.locator('.m2-result-card').first()).toBeVisible()
  })

  test('results scroll and filters survive detail Back, including the UI arrow', async ({ page }) => {
    await finishOnboarding(page)
    await page.locator('.m2-mode-switch > button').first().click()
    await page.getByTestId('open-location').click()
    const results = page.getByTestId('mobile-results')
    await expect(results.locator('.m2-result-card')).not.toHaveCount(0)
    await results.evaluate((element) => { element.scrollTop = 850 })
    const before = await results.evaluate((element) => element.scrollTop)
    expect(before).toBeGreaterThan(400)
    const url = page.url()
    await results.locator('.m2-result-card').nth(5).locator('.m2-result-card__image-button').click()
    await expect(page.locator('.listing-page h1')).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(url)
    await expect(results.locator('.m2-result-card').first()).toBeAttached()
    await expect.poll(() => results.evaluate((element) => element.scrollTop)).toBeGreaterThan(before - 100)
    await results.locator('.m2-result-card').nth(5).locator('.m2-result-card__image-button').click()
    await page.getByRole('button', { name: 'Volver', exact: true }).click()
    await expect(results).toBeVisible()
  })

  test('menu → my listings → edit uses the actual history; direct detail has a fallback', async ({ page }) => {
    await finishOnboarding(page)
    await page.evaluate(() => {
      const key = '112233:listings:v3'
      const payload = JSON.parse(localStorage.getItem(key) ?? '{"version":3,"data":[]}')
      payload.data[0].ownerUserId = 'tenant-demo'
      payload.data[0].userCreated = true
      localStorage.setItem(key, JSON.stringify(payload))
      localStorage.setItem('112233:session:v1', JSON.stringify('tenant-demo'))
      localStorage.setItem('112233:mobile-onboarding:v1', 'done')
    })
    await page.reload()
    await expect(page.getByTestId('open-location')).toBeVisible()
    await page.locator('.m2-bottom-nav button').last().click()
    await expect(page).toHaveURL(/#\/menu$/)
    await page.getByRole('button', { name: /ver y crear anuncios/i }).click()
    await expect(page.locator('.manage-card')).toHaveCount(1)
    await page.getByRole('link', { name: /editar/i }).click()
    await expect(page.getByRole('heading', { name: /editar habitación/i })).toBeVisible()
    await page.locator('.listing-edit-back').click()
    await expect(page.locator('.manage-card')).toHaveCount(1)
    await page.locator('.owner-mobile-appbar button').click()
    await expect(page).toHaveURL(/#\/menu$/)

    const id = await page.evaluate(() => JSON.parse(localStorage.getItem('112233:listings:v3')!).data[0].id as string)
    const deepLink = await page.context().newPage()
    await deepLink.setViewportSize({ width: 390, height: 844 })
    await deepLink.goto(`/#/habitacion/${id}`)
    await expect(deepLink.locator('.listing-page h1')).toBeVisible()
    await deepLink.getByRole('button', { name: 'Volver', exact: true }).click()
    await expect(deepLink).toHaveURL(/#\/buscar/)
  })
})

test('desktop results → detail → browser Back restores the result route', async ({ page }) => {
  await page.goto('/#/buscar?q=Tenerife&alquiler=long')
  await expect(page.locator('.search-page')).toBeVisible()
  const result = page.locator('.property-card a[href*="habitacion/"]').first()
  await expect(result).toBeVisible()
  const before = page.url()
  await result.click()
  await expect(page.locator('.listing-page h1')).toBeVisible()
  await page.goBack()
  await expect(page).toHaveURL(before)
  await expect(page.locator('.property-card').first()).toBeVisible()
})

test('desktop map → detail → Back restores camera and selected listing', async ({ page }) => {
  await page.goto('/#/buscar?q=Tenerife&alquiler=long&vista=mapa&mapLat=28.12526&mapLng=-16.76163&mapZoom=12.00')
  const map = page.locator('.results-map__canvas')
  await expect(map).toHaveAttribute('data-map-instance', 'google-ready', { timeout: 20_000 })
  await expect(map).toHaveAttribute('data-map-zoom', '12')
  await map.evaluate((element) => element.dispatchEvent(new WheelEvent('wheel', { bubbles: true, deltaY: -100 })))
  await expect(map).toHaveAttribute('data-map-zoom', '13')
  await expect(page).toHaveURL(/mapZoom=13\.00/)
  await page.locator('.map-list-alternative button').first().evaluate((element: HTMLElement) => element.click())
  const preview = page.getByTestId('desktop-same-address-carousel')
  await expect(preview).toBeVisible()
  const selectedId = await preview.getAttribute('data-listing-id')
  await expect(page).toHaveURL(/mapZoom=13\.00/)
  const mapUrl = page.url()
  await preview.locator('a[href*="/habitacion/"]').first().click()
  await expect(page.locator('.listing-page h1')).toBeVisible()
  await page.goBack()
  await expect(page).toHaveURL(mapUrl)
  await expect(preview).toHaveAttribute('data-listing-id', selectedId!)
  await expect(map).toHaveAttribute('data-map-zoom', '13')
  await expect(map).toHaveAttribute('data-map-center', '28.125260,-16.761630')
})

test('detail → related detail → Back restores the first detail', async ({ page }) => {
  await page.goto('/#/habitacion/arme%C3%B1ime-luminosa-01')
  await expect(page.locator('.listing-page h1')).toBeVisible()
  const firstUrl = page.url()
  const related = page.locator('.listing-similar .property-card a[href*="habitacion/"]').first()
  await expect(related).toBeVisible()
  await related.click()
  await expect(page.locator('.listing-page h1')).toBeVisible()
  expect(page.url()).not.toBe(firstUrl)
  await page.goBack()
  await expect(page).toHaveURL(firstUrl)
  await expect(page.locator('.listing-page h1')).toBeVisible()
})

test('search and map bookmarks survive reload', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => localStorage.setItem('112233:mobile-onboarding:v1', 'done'))
  await page.goto('/#/buscar?q=Arona&alquiler=long&precioMax=600')
  await expect(page.getByTestId('mobile-results')).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('mobile-results')).toBeVisible()
  await expect(page).toHaveURL(/q=Arona/)
  await page.goto('/#/buscar?q=Tenerife&vista=mapa&mapLat=28.29160&mapLng=-16.62910&mapZoom=11.00')
  await expect(page.getByTestId('google-map')).toHaveAttribute('data-map-interaction', 'interactive', { timeout: 20_000 })
  await page.reload()
  await expect(page.getByTestId('google-map')).toHaveAttribute('data-map-interaction', 'interactive', { timeout: 20_000 })
})
