import { useState, type FormEvent } from 'react'
import { ArrowRight, CheckCircle2, Cookie, FileText, HelpCircle, Mail, MessageCircle, Search, Shield, Upload } from 'lucide-react'
import { Link, useLocation } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { FormField } from '@/components/forms'

type PageContent = { eyebrow: string; title: string; intro: string; icon: typeof Search; sections: { title: string; text: string; bullets?: string[] }[] }

const pages: Record<string, PageContent> = {
  '/sobre-nosotros': { eyebrow: 'Sobre 112233.es', title: 'Una plataforma hecha solo para habitaciones.', intro: 'Nacimos en Tenerife para ordenar un mercado disperso y hacer visibles las condiciones que suelen aparecer demasiado tarde.', icon: MessageCircle, sections: [{ title: 'Nuestro propósito', text: 'Reducir conversaciones incompatibles y ayudar a que inquilinos y anunciantes tomen decisiones con mejor información.' }, { title: 'Qué hacemos diferente', text: 'Estructuramos precio, gastos, fianza, disponibilidad y convivencia desde el primer vistazo.', bullets: ['Solo habitaciones y estudios compactos', 'Ubicación aproximada por privacidad', 'Contacto directo y condiciones confirmadas'] }, { title: 'Ámbito actual', text: 'La experiencia de demostración se centra en Tenerife. La arquitectura permite ampliar a otras islas y ciudades.' }] },
  '/como-funciona': { eyebrow: 'Guía rápida', title: 'De la búsqueda al primer mensaje.', intro: 'Tres pasos claros para encontrar una habitación compatible o publicar la que tienes libre.', icon: Search, sections: [{ title: '1. Busca y filtra', text: 'Elige zona, presupuesto, fecha y condiciones de convivencia.' }, { title: '2. Compara con contexto', text: 'Revisa gastos, fianza, disponibilidad, vivienda y perfil del anunciante.' }, { title: '3. Contacta', text: 'Confirma que cumples las condiciones y habla por WhatsApp, teléfono o mensaje interno.' }] },
  '/ayuda': { eyebrow: 'Centro de ayuda', title: 'Respuestas para avanzar sin atascarte.', intro: 'Encuentra ayuda sobre búsquedas, contactos, anuncios, seguridad y cuenta.', icon: HelpCircle, sections: [{ title: 'Buscar habitación', text: 'Usa filtros de precio, zona, disponibilidad y convivencia. Puedes guardar resultados como favoritos.' }, { title: 'Contactar con un anuncio', text: 'Antes de escribir, confirma que cumples las condiciones principales. Nunca envíes dinero sin verificar la vivienda y las condiciones.' }, { title: 'Publicar y moderar', text: 'Los anuncios pasan por revisión básica. Los estados aparecen en Mis anuncios.' }, { title: 'Problemas y denuncias', text: 'Usa “Denunciar anuncio” para informar de datos incorrectos, fraude o contenido prohibido.' }] },
  '/terminos': { eyebrow: 'Legal', title: 'Términos de uso', intro: 'Condiciones generales de la demostración de 112233.es.', icon: FileText, sections: [{ title: 'Uso del servicio', text: 'La plataforma facilita el contacto entre personas interesadas. No es parte del contrato de alquiler ni garantiza la identidad, solvencia o disponibilidad.' }, { title: 'Contenido de usuarios', text: 'Quien publica es responsable de la exactitud, legalidad y actualización de su anuncio.' }, { title: 'Moderación', text: 'Podemos ocultar o retirar contenido que incumpla las normas o genere un riesgo razonable para la comunidad.' }] },
  '/privacidad': { eyebrow: 'Legal', title: 'Privacidad', intro: 'Qué datos serían necesarios y cómo deberían protegerse al conectar el backend.', icon: Shield, sections: [{ title: 'Datos de cuenta', text: 'Nombre, email, teléfono y preferencias se usarían para operar la cuenta y facilitar contactos solicitados.' }, { title: 'Ubicación', text: 'Las direcciones exactas no se muestran públicamente. El mapa usa una posición aproximada.' }, { title: 'Tus derechos', text: 'La versión productiva deberá ofrecer acceso, rectificación, portabilidad y eliminación mediante procesos verificables.' }] },
  '/cookies': { eyebrow: 'Legal', title: 'Política de cookies', intro: 'La demo solo usa almacenamiento local para favoritos y estado de interfaz.', icon: Cookie, sections: [{ title: 'Necesarias', text: 'Mantienen preferencias y permiten que la experiencia funcione.' }, { title: 'Analítica', text: 'No está conectada en esta demo. En producción requeriría configuración, minimización y consentimiento cuando corresponda.' }, { title: 'Control', text: 'La versión final deberá incluir un gestor de consentimiento compatible con la configuración real.' }] },
  '/normas-de-publicacion': { eyebrow: 'Calidad y convivencia', title: 'Normas de publicación', intro: 'Anuncios claros, actuales y respetuosos generan mejores contactos.', icon: Upload, sections: [{ title: 'Información obligatoria', text: 'Precio, gastos, fianza, disponibilidad, estancia mínima, tipo de habitación y condiciones.' }, { title: 'Fotografías', text: 'Deben mostrar la habitación ofrecida y no incluir marcas de agua, datos personales ni imágenes engañosas.' }, { title: 'Contenido no permitido', text: 'Fraude, duplicados, contenido sexual, direcciones públicas y criterios discriminatorios contrarios a la normativa aplicable.' }, { title: 'Actualización', text: 'Oculta o finaliza el anuncio cuando la habitación deje de estar disponible.' }] },
}

export function ContactPage() {
  const [sent, setSent] = useState(false)
  const submit = (event: FormEvent) => { event.preventDefault(); setSent(true) }
  return <div className="info-page container"><header className="info-hero"><span className="eyebrow">Contacto</span><h1>¿En qué podemos ayudarte?</h1><p>Cuéntanos el problema con suficiente detalle. Respondemos en horario de Canarias.</p></header><div className="contact-layout"><div className="contact-options"><div><Mail /><h2>Email</h2><p>hola@112233.es</p><span>Respuesta habitual en 1 día laborable</span></div><div><MessageCircle /><h2>Ayuda con anuncios</h2><p>Incluye la referencia del anuncio</p><span>No envíes documentación sensible</span></div></div>{sent ? <Alert><CheckCircle2 /><AlertTitle>Mensaje recibido</AlertTitle><AlertDescription>Te responderemos en el email indicado. Tu referencia es 112-260719.</AlertDescription></Alert> : <form className="contact-form" onSubmit={submit}><div className="form-grid"><FormField label="Nombre" htmlFor="contact-name"><Input id="contact-name" required /></FormField><FormField label="Email" htmlFor="contact-email"><Input id="contact-email" type="email" required /></FormField></div><FormField label="Motivo" htmlFor="contact-reason"><select id="contact-reason"><option>Duda sobre una habitación</option><option>Problema con mi anuncio</option><option>Seguridad o fraude</option><option>Cuenta y acceso</option><option>Otro</option></select></FormField><FormField label="Mensaje" htmlFor="contact-message"><Textarea id="contact-message" rows={7} required /></FormField><Button size="lg">Enviar consulta</Button></form>}</div></div>
}

export function InfoPage() {
  const { pathname } = useLocation()
  if (pathname === '/contacto') return <ContactPage />
  const content = pages[pathname] ?? pages['/sobre-nosotros']
  const Icon = content.icon
  return <div className="info-page container"><header className="info-hero"><div className="info-icon"><Icon /></div><span className="eyebrow">{content.eyebrow}</span><h1>{content.title}</h1><p>{content.intro}</p></header><div className="info-layout"><aside><nav aria-label="En esta sección">{Object.entries(pages).map(([path, page]) => <Link key={path} to={path} aria-current={pathname === path ? 'page' : undefined}>{page.title}</Link>)}</nav></aside><article>{content.sections.map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.text}</p>{section.bullets ? <ul>{section.bullets.map((bullet) => <li key={bullet}><CheckCircle2 />{bullet}</li>)}</ul> : null}</section>)}<div className="info-cta"><h2>¿Necesitas una respuesta concreta?</h2><p>El centro de ayuda reúne preguntas habituales y nuestro equipo puede revisar casos específicos.</p><div><Button asChild><Link to="/ayuda">Ir a ayuda <ArrowRight data-icon="inline-end" /></Link></Button><Button asChild variant="outline"><Link to="/contacto">Contactar</Link></Button></div></div></article></div></div>
}
